import React from "react";
import { Container } from "@mui/material";
import { BreadcrumbNav } from "./navigation/BreadcrumbNav";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body suppressHydrationWarning>
        <Container>
          <BreadcrumbNav />
          {children}
        </Container>
      </body>
    </html>
  );
};

export default RootLayout;
